### PR TITLE
Fix support for non-apphost scenarios by providing an array

### LINKED ISSUE #64: Test the `UseAppHost =false` scenario
This should start the container with `dotnet <targetfile>`

### PR DESCRIPTION
**Pull request by baronfel**
Fixes #64

`UseAppHost` right now sets an `EntryPoint` of `"dotnet <app>"`, which is treated as a single argument to the shell. Instead we should detect this case and provide multiple arguments.

I'm leaning more into Items instead of Properties here. I think I'm ok with this. It doesn't feel horrible here?

### CODE REVIEW

File: System.Containers/Image.cs [hunk 1]
```diff
@@ -67,15 +69,15 @@ public void SetEntrypoint(string executable, string[]? args = null)
...
-        configObject["Entrypoint"] = executable;
+        configObject["Entrypoint"] = ToJsonArray(executableArgs);
 
         if (args is null)
         {
             configObject.Remove("Cmd");
         }
         else
         {
-            configObject["Cmd"] = new JsonArray(args.Where(s => !string.IsNullOrEmpty(s)).Select(s =>(JsonObject)s).ToArray());
```
Comment (baronfel) [inline System.Containers/Image.cs:78]: there was a small bug here - string can't be cast to JsonObject directly, you need to cast to JsonValue.

File: Test.System.Containers.Filesystem/TargetsTests.cs [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+            ["UseAppHost"] = useAppHost.ToString()
+        });
+        if (project.Build("ComputeContainerConfig"))
+        {
+            var computedEntrypointArgs = project.GetItems("ContainerEntrypoint").Select(i => i.EvaluatedInclude).ToArray();
+            foreach (var (First, Second) in entrypointArgs.Zip(computedEntrypointArgs)) {
+                Assert.AreEqual(First, Second);
+            }
+        }
+    }
```
Comment (baronfel) [inline Test.System.Containers.Filesystem/TargetsTests.cs:57]: I'm pretty happy with this level of tests - I think we can get a lot of value sanity-checking the targets and tasks this way.

File: Test.System.Containers.Filesystem/CurrentFile.cs [hunk 3]
```diff
@@ -0,0 +1,12 @@
+using System.Runtime.CompilerServices;
+
+namespace Test.System.Containers;
+
+public static class CurrentFile
+{
+    public static string Path([CallerFilePath] string file = "") => file;
```
Comment (baronfel) [inline Test.System.Containers.Filesystem/CurrentFile.cs:7]: CallerFilePath is so cool :)

File: System.Containers.Tasks/build/System.Containers.Tasks.targets [hunk 4]
```diff
@@ -1,11 +1,18 @@
 <Project>
+    <Import Condition="'$(_IsTest)' == 'true'" Project="$(MSBuildThisFileDirectory)System.Containers.Tasks.props" />
```
[the remark this answers is not in the document]
Comment (BenVillalobos) [reply System.Containers.Tasks/build/System.Containers.Tasks.targets:2]: In theory we could build a test-specific targets file that imports both the props and targets. That's one way to avoid modifying the shipping targets for a test scenario

File: Test.System.Containers.Filesystem/CurrentFile.cs (hunk 3 above)
Comment (BenVillalobos) [reply Test.System.Containers.Filesystem/CurrentFile.cs:7]: Today I learned 😮

File: Test.System.Containers.Filesystem/TargetsTests.cs [hunk 5]
```diff
@@ -0,0 +1,58 @@
...
+
+    private Project InitProject(Dictionary<string, string> bonusProps) {
+        var targetsFile = CurrentFile.Relative("../System.Containers.Tasks/build/System.Containers.Tasks.targets");
+        var props = new Dictionary<string, string>();
+        // required parameters
+        props["TargetFileName"] = "foo.dll";
+        props["AssemblyName"] = "foo";
+        props["_TargetFrameworkVersionWithoutV"] = "7.0";
+        props["_NativeExecutableExtension"] = ".exe"; //TODO: windows/unix split here
+        props["Version"] = "1.0.0"; // TODO: need to test non-compliant version strings here
```
Comment (BenVillalobos) [inline Test.System.Containers.Filesystem/TargetsTests.cs:25]: Good point, `ParseContainerProperties` doesn't check tags yet.

File: System.Containers.Tasks/build/System.Containers.Tasks.targets (hunk 4 above)
[the remark this answers is not in the document]
Comment (baronfel) [reply System.Containers.Tasks/build/System.Containers.Tasks.targets]: this was pretty easy to do by glomming together the file contents and jamming that into a temp dir. Works for now :D

**Comment by baronfel** [comment]
Alright, much happier with this now. There's minimal test-specific changes to the props/targets, and we've got good coverage on the Apphost-driven flags now, as well as a good base to test further changes to the targets.

File: Test.Microsoft.NET.Build.Containers.Filesystem/TargetsTests.cs [hunk 6]
```diff
@@ -0,0 +1,87 @@
...
+        {
+            props[kvp.Key] = kvp.Value;
+        }
+        return collection.LoadProject(CombinedTargetsLocation, props, null);
+    }
+
+    [DataRow(true, "/app/foo.exe")]
+    [DataRow(false, "dotnet", "/app/foo.dll")]
+    [TestMethod]
+    public void CanSetEntrypointArgsToUseAppHost(bool useAppHost, params string[] entrypointArgs)
```
Comment (BenVillalobos) [inline Test.Microsoft.NET.Build.Containers.Filesystem/TargetsTests.cs:72]: oh nice, this covers https://github.com/rainersigwald/containers/issues/64!

File: Test.Microsoft.NET.Build.Containers.Filesystem/TargetsTests.cs [hunk 7]
```diff
@@ -0,0 +1,87 @@
...
+public class TargetsTests
+{
+    private static string CombinedTargetsLocation;
+
+    private static string CombineFiles(string propsFile, string targetsFile)
+    {
+        var propsContent = File.ReadAllLines(propsFile);
+        var targetsContent = File.ReadAllLines(targetsFile);
+        var combinedContent = new List<string>();
+        combinedContent.AddRange(propsContent[..^1]);
```
Comment (BenVillalobos) [inline Test.Microsoft.NET.Build.Containers.Filesystem/TargetsTests.cs:17]: TIL! https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/member-access-operators#index-from-end-operator-

**Review by BenVillalobos — APPROVED** [review]

File: Test.Microsoft.NET.Build.Containers.Filesystem/TargetsTests.cs (hunk 6 above)
Comment (BenVillalobos) [reply Test.Microsoft.NET.Build.Containers.Filesystem/TargetsTests.cs:72]: ^ not a blocking question

File: Test.Microsoft.NET.Build.Containers.Filesystem/TargetsTests.cs [hunk 8]
```diff
@@ -0,0 +1,87 @@
...
+    public void CanSetEntrypointArgsToUseAppHost(bool useAppHost, params string[] entrypointArgs)
+    {
+        var project = InitProject(new()
+        {
+            ["UseAppHost"] = useAppHost.ToString()
+        });
+        if (project.Build("ComputeContainerConfig"))
+        {
+            var computedEntrypointArgs = project.GetItems("ContainerEntrypoint").Select(i => i.EvaluatedInclude).ToArray();
+            foreach (var (First, Second) in entrypointArgs.Zip(computedEntrypointArgs))
```
Comment (rainersigwald) [inline Test.Microsoft.NET.Build.Containers.Filesystem/TargetsTests.cs:81]: Wow, the F# is strong in you! :)

File: Test.Microsoft.NET.Build.Containers.Filesystem/TargetsTests.cs [hunk 9]
```diff
@@ -0,0 +1,87 @@
...
+        {
+            // new Microsoft.Build.Logging.BinaryLogger() {CollectProjectImports = Microsoft.Build.Logging.BinaryLogger.ProjectImportsCollectionMode.Embed, Verbosity = LoggerVerbosity.Diagnostic, Parameters = "LogFile=blah.binlog" },
+            // new Microsoft.Build.Logging.ConsoleLogger(LoggerVerbosity.Detailed)
+        };
+        var collection = new ProjectCollection(null, loggers, ToolsetDefinitionLocations.Default);
+        foreach (var kvp in bonusProps)
+        {
+            props[kvp.Key] = kvp.Value;
+        }
+        return collection.LoadProject(CombinedTargetsLocation, props, null);
```
Comment (rainersigwald) [inline Test.Microsoft.NET.Build.Containers.Filesystem/TargetsTests.cs:66]: This is a sneaky approach to testing the new logic, I like it.

File: Test.Microsoft.NET.Build.Containers.Filesystem/TargetsTests.cs [hunk 10]
```diff
@@ -0,0 +1,87 @@
...
+    [DataRow(true, "/app/foo.exe")]
+    [DataRow(false, "dotnet", "/app/foo.dll")]
+    [TestMethod]
+    public void CanSetEntrypointArgsToUseAppHost(bool useAppHost, params string[] entrypointArgs)
+    {
+        var project = InitProject(new()
+        {
+            ["UseAppHost"] = useAppHost.ToString()
+        });
+        if (project.Build("ComputeContainerConfig"))
```
Comment (rainersigwald) [inline Test.Microsoft.NET.Build.Containers.Filesystem/TargetsTests.cs:78]:
```suggestion
        Assert.IsTrue(project.Build("ComputeContainerConfig"));
```

?

File: Test.Microsoft.NET.Build.Containers.Filesystem/TargetsTests.cs (hunk 6 above)
Comment (baronfel) [reply Test.Microsoft.NET.Build.Containers.Filesystem/TargetsTests.cs:72]: To be honest, I'm perfectly satisfied with this level of testing, given that I also know how 'first-class' the UseAppHost flag is.

File: Test.Microsoft.NET.Build.Containers.Filesystem/TargetsTests.cs (hunk 7 above)
Comment (baronfel) [reply Test.Microsoft.NET.Build.Containers.Filesystem/TargetsTests.cs:17]: yeah man, slicing is the bees knees :)

File: Microsoft.NET.Build.Containers/CreateNewImage.cs [hunk 11]
```diff
@@ -59,12 +59,12 @@ public class CreateNewImage : Microsoft.Build.Utilities.Task
...
     /// </summary>
     [Required]
-    public string Entrypoint { get; set; }
+    public ITaskItem[] Entrypoint { get; set; }
 
     /// <summary>
     /// Arguments to pass alongside Entrypoint.
     /// </summary>
-    public string EntrypointArgs { get; set; }
+    public ITaskItem[] EntrypointArgs { get; set; }
```
[the remark this answers is not in the document]
Comment (baronfel) [reply Microsoft.NET.Build.Containers/CreateNewImage.cs:67]: This is an excellent question, and I believe right now nothing actually touches/uses EntrypointArgs. We will likely need to for  rc1, so I was mostly thinking that `Entrypoint` would virtually always be auto-generated by the targets, and EntrypointArgs would be a user-modification point (at least in the ideal use case). I'm unsure how that will hold up to actual user testing, though.

File: Test.Microsoft.NET.Build.Containers.Filesystem/TargetsTests.cs [hunk 12]
```diff
@@ -0,0 +1,87 @@
...
+{
+    private static string CombinedTargetsLocation;
+
+    private static string CombineFiles(string propsFile, string targetsFile)
+    {
+        var propsContent = File.ReadAllLines(propsFile);
+        var targetsContent = File.ReadAllLines(targetsFile);
+        var combinedContent = new List<string>();
+        combinedContent.AddRange(propsContent[..^1]);
+        combinedContent.AddRange(targetsContent[1..]);
```
[the remark this answers is not in the document]
Comment (baronfel) [reply Test.Microsoft.NET.Build.Containers.Filesystem/TargetsTests.cs:18]: I felt (and still feel) like a total hack, but I stand by it! The 'right' way would be loading the xml documents and taking the children of the root nodes, but whyyyyyyy

File: Test.Microsoft.NET.Build.Containers.Filesystem/TargetsTests.cs (hunk 8 above)
Comment (baronfel) [reply Test.Microsoft.NET.Build.Containers.Filesystem/TargetsTests.cs:81]: Combined iteration, it's a beautiful thing. There are so many wonderful functions in the [Seq module](https://fsharp.github.io/fsharp-core-docs/reference/fsharp-collections-seqmodule.html) for working with collections that I always miss when in C#.

File: Test.Microsoft.NET.Build.Containers.Filesystem/TargetsTests.cs (hunk 9 above)
Comment (baronfel) [reply Test.Microsoft.NET.Build.Containers.Filesystem/TargetsTests.cs:66]: I'll gladly take grudging approval from @rainersigwald  :D

**Comment by baronfel** [comment]
@rainersigwald's suggestions surfaced that the tests had been failing, but I hadn't been asserting on their success so we never saw the failures.

After taking that change, I had to make some changes to the tests so that they continued to pass (after taking the targets fixes from main).
